name: ci
on: [push, pull_request]
jobs:
  build-MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install autoconf automake libtool shunit2 gnu-sed cppcheck
    - run: ./build.sh
    - run: sudo make install
    - run: make distclean
